"""AI Act Art. 50 — disclosure-labelling AUDIT.

Strictly: this checks whether the platform has applied the AI-Act-mandated
AI-generated-content label, given that there are reasonable indicators the
content is AI-involved. We never claim that a video is AI-generated; we
identify a potential platform disclosure-labelling failure.
"""

from __future__ import annotations

import re

from ..config import SETTINGS
from ..models import ComplianceGap, FactCheckMatch, VideoMetadata

_AI_HASHTAG_RE = re.compile(
    r"#(ai(?:art|generated|content|video|audio)?|deepfake|synthetic|midjourney|sora|veo)\b",
    re.IGNORECASE,
)
_AI_TEXT_HINTS = re.compile(
    r"\b(generated by ai|ai[- ]generated|deepfake|synthetic media|made with (?:ai|midjourney|sora))\b",
    re.IGNORECASE,
)


def detect(
    metadata: VideoMetadata,
    matches: list[FactCheckMatch],
    synthetic_likelihood: float | None,
) -> ComplianceGap | None:
    indicators: list[str] = []

    # Indicator 1: uploader-declared in description / hashtags
    if any(_AI_HASHTAG_RE.search(h) for h in metadata.hashtags):
        indicators.append("ai_hashtag_present")
    if metadata.description and _AI_TEXT_HINTS.search(metadata.description):
        indicators.append("ai_text_disclosure_in_description")

    # Indicator 2: ClaimReview match flagged as AI-generated political audio
    if any("ai_generated" in m.factcheck_id.lower() or "deepfake" in m.title.lower()
           for m in matches):
        indicators.append("edmo_ai_generated_match")

    # Indicator 3: third-party synthetic-media likelihood (metadata enrichment
    # only — we never fire the gap on this signal alone unless it's very high)
    if (
        synthetic_likelihood is not None
        and synthetic_likelihood >= SETTINGS.art50_synthetic_likelihood_threshold
    ):
        indicators.append(
            f"third_party_synthetic_likelihood>={SETTINGS.art50_synthetic_likelihood_threshold}"
        )

    if not indicators:
        return None
    if metadata.has_platform_ai_label:
        return None  # Platform did its job.

    return ComplianceGap(
        article_ref="AI Act Art. 50",
        article_short="Disclosure label absent",
        severity="high" if "third_party_synthetic_likelihood" in str(indicators) else "medium",
        description=(
            "Reasonable indicators of AI-involvement are present, but the "
            "platform has not surfaced the AI Act-mandated disclosure label. "
            "This is a potential platform-level disclosure failure under "
            "Article 50 of Regulation (EU) 2024/1689 (enforceable 2 Aug 2026)."
        ),
        evidence={
            "indicators": indicators,
            "platform": metadata.platform.value,
            "has_platform_ai_label": metadata.has_platform_ai_label,
            "synthetic_likelihood": synthetic_likelihood,
            "scope_note": (
                "Narrative Radar does not classify content as AI-generated. "
                "We audit whether the platform applied the legally required label."
            ),
        },
    )
