import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { api } from "../lib/api";
export function LegalBasis() {
    const [refs, setRefs] = useState(null);
    useEffect(() => {
        api.legalRefs().then(setRefs);
    }, []);
    return (_jsxs("div", { className: "flex w-full flex-col gap-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "font-serif text-2xl text-eu-ink font-semibold", children: "Legal basis" }), _jsx("p", { className: "text-sm text-eu-slate-500 mt-0.5", children: "The articles Narrative Radar maps indicators against. We do not make legal determinations \u2014 qualified review is required." })] }), !refs ? (_jsx("div", { className: "text-eu-slate-500 text-sm", children: "Loading\u2026" })) : (_jsx("div", { className: "space-y-4", children: Object.entries(refs).map(([ref, body]) => (_jsxs("article", { className: "surface p-5", children: [_jsxs("div", { className: "flex items-baseline justify-between gap-3 mb-1", children: [_jsxs("h2", { className: "font-serif text-lg text-eu-ink font-semibold", children: [ref, " ", _jsxs("span", { className: "text-sm text-eu-slate-500 font-sans font-normal", children: ["\u2014 ", body.short] })] }), body.enforcement_date && (_jsxs("span", { className: "badge bg-amber-100 text-amber-800 border border-amber-200", children: ["enforceable ", body.enforcement_date] }))] }), _jsxs("div", { className: "text-xs text-eu-slate-500 font-mono mb-2", children: [body.instrument, " \u00B7", " ", _jsx("a", { href: body.official_url, target: "_blank", rel: "noreferrer", className: "text-eu-blue underline", children: "EUR-Lex" })] }), _jsx("p", { className: "text-sm text-eu-slate-700", children: body.summary }), _jsxs("p", { className: "text-sm text-eu-slate-600 italic mt-3 border-l-2 border-eu-blue/30 pl-3", children: [_jsx("span", { className: "font-semibold not-italic text-eu-ink", children: "Indicator basis:" }), " ", body.indicator_basis] })] }, ref))) })), _jsxs("div", { className: "surface p-5 bg-amber-50 border-amber-200 text-sm text-amber-900", children: [_jsx("strong", { children: "What we are not." }), " Narrative Radar does not classify content as \"disinformation\" or \"AI-generated\". We surface indicators of potential platform obligation failures, grounded in EDMO / EUvsDisinfo determinations and the platforms' own DSA Transparency Database submissions. Detection of synthetic media is treated as metadata only and never gates a compliance gap on its own."] })] }));
}
